version: '3.4'

services:
  tma_frontend:
    image: node:latest
    working_dir: /usr/src/app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/tma:/usr/src/app
    command: sh -c "npm install && npm run dev-host"

  ngrok:
    image: ngrok/ngrok:alpine
    env_file:
      - .env
    command: 'http --domain="$TMA_DOMAIN" tma_frontend:5173'
    ports:
      - '4040:4040'
    expose:
      - '4040'
    depends_on:
      - tma_frontend